// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_HomePage.h"
#include "screens/ui_Weather.h"
#include "screens/ui_DirectionMaAxAndGy.h"
#include "screens/ui_Chronometre.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_home_page_png);    // assets/Home page.png
LV_IMG_DECLARE(ui_img_nav_button_right_circle_28x28_png);    // assets/nav_button_right_circle_28x28.png
LV_IMG_DECLARE(ui_img_nav_button_left_circle_28x28_png);    // assets/nav_button_left_circle_28x28.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_logo_pressure_gauge_28x28_png);    // assets/logo_pressure_gauge_28x28.png
LV_IMG_DECLARE(ui_img_logo_compass_28x28_v1_png);    // assets/logo_compass_28x28_v1.png
LV_IMG_DECLARE(ui_img_xyz_30x30_exact_png);    // assets/xyz_30x30_exact.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
