// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT ButtonON

lv_obj_t * ui_ButtonON_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ButtonON;
    cui_ButtonON = lv_button_create(comp_parent);
    lv_obj_set_width(cui_ButtonON, 100);
    lv_obj_set_height(cui_ButtonON, 50);
    lv_obj_set_x(cui_ButtonON, -101);
    lv_obj_set_y(cui_ButtonON, 85);
    lv_obj_set_align(cui_ButtonON, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonON, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_ButtonON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONON_NUM);
    children[UI_COMP_BUTTONON_BUTTONON] = cui_ButtonON;
    lv_obj_add_event_cb(cui_ButtonON, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ButtonON, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ButtonON_create_hook(cui_ButtonON);
    return cui_ButtonON;
}

