// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Chronometre = NULL;
lv_obj_t * ui_Bakground = NULL;
lv_obj_t * ui_chronometer = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_ConterContainer = NULL;
lv_obj_t * ui_LabelHH = NULL;
lv_obj_t * ui_LabelSeparator8 = NULL;
lv_obj_t * ui_LabelMM = NULL;
lv_obj_t * ui_LabelSeparator5 = NULL;
lv_obj_t * ui_LabelSS = NULL;
lv_obj_t * ui_LabelLettres = NULL;
lv_obj_t * ui_ButtonStartContainer = NULL;
lv_obj_t * ui_ButtonStart = NULL;
lv_obj_t * ui_LabelStart = NULL;
lv_obj_t * ui_ButtonResetContainer = NULL;
lv_obj_t * ui_ButtonReset = NULL;
lv_obj_t * ui_LabelReset = NULL;
lv_obj_t * ui_ButtonStopContainer = NULL;
lv_obj_t * ui_ButtonStop = NULL;
lv_obj_t * ui_LabelStop = NULL;
lv_obj_t * ui_next4 = NULL;
lv_obj_t * ui_previous4 = NULL;
// event funtions

// build funtions

void ui_Chronometre_screen_init(void)
{
    ui_Chronometre = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Chronometre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bakground = lv_image_create(ui_Chronometre);
    lv_image_set_src(ui_Bakground, &ui_img_home_page_png);
    lv_obj_set_width(ui_Bakground, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Bakground, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Bakground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bakground, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Bakground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chronometer = lv_label_create(ui_Chronometre);
    lv_obj_set_width(ui_chronometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chronometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chronometer, -3);
    lv_obj_set_y(ui_chronometer, -108);
    lv_obj_set_align(ui_chronometer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chronometer, "CHRONOMETRE");
    lv_obj_set_style_text_color(ui_chronometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chronometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chronometer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Chronometre);
    lv_obj_set_width(ui_Arc1, 183);
    lv_obj_set_height(ui_Arc1, 180);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    ui_ConterContainer = lv_obj_create(ui_Chronometre);
    lv_obj_remove_style_all(ui_ConterContainer);
    lv_obj_set_width(ui_ConterContainer, 140);
    lv_obj_set_height(ui_ConterContainer, 35);
    lv_obj_set_x(ui_ConterContainer, 3);
    lv_obj_set_y(ui_ConterContainer, -25);
    lv_obj_set_align(ui_ConterContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHH = lv_label_create(ui_ConterContainer);
    lv_obj_set_width(ui_LabelHH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHH, -55);
    lv_obj_set_y(ui_LabelHH, 4);
    lv_obj_set_align(ui_LabelHH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHH, "00");
    lv_obj_set_style_text_color(ui_LabelHH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHH, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator8 = lv_label_create(ui_ConterContainer);
    lv_obj_set_width(ui_LabelSeparator8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator8, -31);
    lv_obj_set_y(ui_LabelSeparator8, 3);
    lv_obj_set_align(ui_LabelSeparator8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator8, ":");
    lv_obj_set_style_text_color(ui_LabelSeparator8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMM = lv_label_create(ui_ConterContainer);
    lv_obj_set_width(ui_LabelMM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMM, -5);
    lv_obj_set_y(ui_LabelMM, 4);
    lv_obj_set_align(ui_LabelMM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMM, "00");
    lv_obj_set_style_text_color(ui_LabelMM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMM, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator5 = lv_label_create(ui_ConterContainer);
    lv_obj_set_width(ui_LabelSeparator5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator5, 20);
    lv_obj_set_y(ui_LabelSeparator5, 3);
    lv_obj_set_align(ui_LabelSeparator5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator5, ":");
    lv_obj_set_style_text_color(ui_LabelSeparator5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSS = lv_label_create(ui_ConterContainer);
    lv_obj_set_width(ui_LabelSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSS, 43);
    lv_obj_set_y(ui_LabelSS, 3);
    lv_obj_set_align(ui_LabelSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSS, "00");
    lv_obj_set_style_text_color(ui_LabelSS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSS, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLettres = lv_label_create(ui_Chronometre);
    lv_obj_set_width(ui_LabelLettres, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLettres, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLettres, -5);
    lv_obj_set_y(ui_LabelLettres, 8);
    lv_obj_set_align(ui_LabelLettres, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLettres, "HH : MM : SS");
    lv_obj_set_style_text_color(ui_LabelLettres, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLettres, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLettres, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStartContainer = lv_obj_create(ui_Chronometre);
    lv_obj_remove_style_all(ui_ButtonStartContainer);
    lv_obj_set_width(ui_ButtonStartContainer, 73);
    lv_obj_set_height(ui_ButtonStartContainer, 45);
    lv_obj_set_x(ui_ButtonStartContainer, -122);
    lv_obj_set_y(ui_ButtonStartContainer, 52);
    lv_obj_set_align(ui_ButtonStartContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonStartContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonStart = lv_button_create(ui_ButtonStartContainer);
    lv_obj_set_width(ui_ButtonStart, 53);
    lv_obj_set_height(ui_ButtonStart, 33);
    lv_obj_set_x(ui_ButtonStart, -2);
    lv_obj_set_y(ui_ButtonStart, 2);
    lv_obj_set_align(ui_ButtonStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonStart, lv_color_hex(0x0075FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStart = lv_label_create(ui_ButtonStartContainer);
    lv_obj_set_width(ui_LabelStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStart, -2);
    lv_obj_set_y(ui_LabelStart, 3);
    lv_obj_set_align(ui_LabelStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStart, "Start");
    lv_obj_set_style_text_color(ui_LabelStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStart, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResetContainer = lv_obj_create(ui_Chronometre);
    lv_obj_remove_style_all(ui_ButtonResetContainer);
    lv_obj_set_width(ui_ButtonResetContainer, 73);
    lv_obj_set_height(ui_ButtonResetContainer, 45);
    lv_obj_set_x(ui_ButtonResetContainer, 3);
    lv_obj_set_y(ui_ButtonResetContainer, 72);
    lv_obj_set_align(ui_ButtonResetContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonResetContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReset = lv_button_create(ui_ButtonResetContainer);
    lv_obj_set_width(ui_ButtonReset, 57);
    lv_obj_set_height(ui_ButtonReset, 33);
    lv_obj_set_x(ui_ButtonReset, -4);
    lv_obj_set_y(ui_ButtonReset, 2);
    lv_obj_set_align(ui_ButtonReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonReset, lv_color_hex(0xF94848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReset = lv_label_create(ui_ButtonResetContainer);
    lv_obj_set_width(ui_LabelReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelReset, -4);
    lv_obj_set_y(ui_LabelReset, 2);
    lv_obj_set_align(ui_LabelReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReset, "Reset");
    lv_obj_set_style_text_color(ui_LabelReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReset, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStopContainer = lv_obj_create(ui_Chronometre);
    lv_obj_remove_style_all(ui_ButtonStopContainer);
    lv_obj_set_width(ui_ButtonStopContainer, 73);
    lv_obj_set_height(ui_ButtonStopContainer, 45);
    lv_obj_set_x(ui_ButtonStopContainer, 122);
    lv_obj_set_y(ui_ButtonStopContainer, 53);
    lv_obj_set_align(ui_ButtonStopContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonStopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonStop = lv_button_create(ui_ButtonStopContainer);
    lv_obj_set_width(ui_ButtonStop, 53);
    lv_obj_set_height(ui_ButtonStop, 33);
    lv_obj_set_x(ui_ButtonStop, -2);
    lv_obj_set_y(ui_ButtonStop, 2);
    lv_obj_set_align(ui_ButtonStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonStop, lv_color_hex(0xFF6707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStop = lv_label_create(ui_ButtonStopContainer);
    lv_obj_set_width(ui_LabelStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStop, -2);
    lv_obj_set_y(ui_LabelStop, 3);
    lv_obj_set_align(ui_LabelStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStop, "Stop");
    lv_obj_set_style_text_color(ui_LabelStop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStop, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next4 = lv_image_create(ui_Chronometre);
    lv_image_set_src(ui_next4, &ui_img_nav_button_right_circle_28x28_png);
    lv_obj_set_width(ui_next4, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_next4, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_next4, 126);
    lv_obj_set_y(ui_next4, 99);
    lv_obj_set_align(ui_next4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_previous4 = lv_image_create(ui_Chronometre);
    lv_image_set_src(ui_previous4, &ui_img_nav_button_left_circle_28x28_png);
    lv_obj_set_width(ui_previous4, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_previous4, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_previous4, -133);
    lv_obj_set_y(ui_previous4, 100);
    lv_obj_set_align(ui_previous4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previous4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_previous4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Chronometre_screen_destroy(void)
{
    if(ui_Chronometre) lv_obj_del(ui_Chronometre);

    // NULL screen variables
    ui_Chronometre = NULL;
    ui_Bakground = NULL;
    ui_chronometer = NULL;
    ui_Arc1 = NULL;
    ui_ConterContainer = NULL;
    ui_LabelHH = NULL;
    ui_LabelSeparator8 = NULL;
    ui_LabelMM = NULL;
    ui_LabelSeparator5 = NULL;
    ui_LabelSS = NULL;
    ui_LabelLettres = NULL;
    ui_ButtonStartContainer = NULL;
    ui_ButtonStart = NULL;
    ui_LabelStart = NULL;
    ui_ButtonResetContainer = NULL;
    ui_ButtonReset = NULL;
    ui_LabelReset = NULL;
    ui_ButtonStopContainer = NULL;
    ui_ButtonStop = NULL;
    ui_LabelStop = NULL;
    ui_next4 = NULL;
    ui_previous4 = NULL;

}
