// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_CHRONOMETRE_H
#define UI_CHRONOMETRE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Chronometre
extern void ui_Chronometre_screen_init(void);
extern void ui_Chronometre_screen_destroy(void);
extern lv_obj_t * ui_Chronometre;
extern lv_obj_t * ui_Bakground;
extern lv_obj_t * ui_chronometer;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_ConterContainer;
extern lv_obj_t * ui_LabelHH;
extern lv_obj_t * ui_LabelSeparator8;
extern lv_obj_t * ui_LabelMM;
extern lv_obj_t * ui_LabelSeparator5;
extern lv_obj_t * ui_LabelSS;
extern lv_obj_t * ui_LabelLettres;
extern lv_obj_t * ui_ButtonStartContainer;
extern lv_obj_t * ui_ButtonStart;
extern lv_obj_t * ui_LabelStart;
extern lv_obj_t * ui_ButtonResetContainer;
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_LabelReset;
extern lv_obj_t * ui_ButtonStopContainer;
extern lv_obj_t * ui_ButtonStop;
extern lv_obj_t * ui_LabelStop;
extern lv_obj_t * ui_next4;
extern lv_obj_t * ui_previous4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

