// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_DirectionMaAxAndGy = NULL;
lv_obj_t * ui_Bakground1 = NULL;
lv_obj_t * ui_TimeContainer3 = NULL;
lv_obj_t * ui_LabelHour3 = NULL;
lv_obj_t * ui_LabelSeparator9 = NULL;
lv_obj_t * ui_LabelMinute3 = NULL;
lv_obj_t * ui_DateContainer3 = NULL;
lv_obj_t * ui_LabelDay3 = NULL;
lv_obj_t * ui_LabelSeparator11 = NULL;
lv_obj_t * ui_LabelMonth3 = NULL;
lv_obj_t * ui_LabelSeparator7 = NULL;
lv_obj_t * ui_LabelYear3 = NULL;
lv_obj_t * ui_DirectionContainer = NULL;
lv_obj_t * ui_degreDirection = NULL;
lv_obj_t * ui_direction = NULL;
lv_obj_t * ui_gauge = NULL;
lv_obj_t * ui_next3 = NULL;
lv_obj_t * ui_previous3 = NULL;
lv_obj_t * ui_CoordonnesAX = NULL;
lv_obj_t * ui_Axelorometer = NULL;
lv_obj_t * ui_CoordonnesAxlormeter = NULL;
lv_obj_t * ui_Xlabel = NULL;
lv_obj_t * ui_valueOfX = NULL;
lv_obj_t * ui_Ylabel = NULL;
lv_obj_t * ui_valueOfY = NULL;
lv_obj_t * ui_Zlabel = NULL;
lv_obj_t * ui_valueOfZ = NULL;
lv_obj_t * ui_CoordonnesGY = NULL;
lv_obj_t * ui_GYRO = NULL;
lv_obj_t * ui_CoordonnesAxlormeter2 = NULL;
lv_obj_t * ui_Xlabel2 = NULL;
lv_obj_t * ui_valueOfX2 = NULL;
lv_obj_t * ui_Ylabel2 = NULL;
lv_obj_t * ui_valueOfY2 = NULL;
lv_obj_t * ui_Zlabel2 = NULL;
lv_obj_t * ui_valueOfZ2 = NULL;
lv_obj_t * ui_Coordonnes2 = NULL;
// event funtions

// build funtions

void ui_DirectionMaAxAndGy_screen_init(void)
{
    ui_DirectionMaAxAndGy = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DirectionMaAxAndGy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DirectionMaAxAndGy, lv_color_hex(0x076EE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionMaAxAndGy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bakground1 = lv_image_create(ui_DirectionMaAxAndGy);
    lv_image_set_src(ui_Bakground1, &ui_img_home_page_png);
    lv_obj_set_width(ui_Bakground1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Bakground1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Bakground1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bakground1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Bakground1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeContainer3 = lv_obj_create(ui_DirectionMaAxAndGy);
    lv_obj_remove_style_all(ui_TimeContainer3);
    lv_obj_set_width(ui_TimeContainer3, 88);
    lv_obj_set_height(ui_TimeContainer3, 26);
    lv_obj_set_x(ui_TimeContainer3, -98);
    lv_obj_set_y(ui_TimeContainer3, -90);
    lv_obj_set_align(ui_TimeContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHour3 = lv_label_create(ui_TimeContainer3);
    lv_obj_set_width(ui_LabelHour3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour3, -29);
    lv_obj_set_y(ui_LabelHour3, -4);
    lv_obj_set_align(ui_LabelHour3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour3, "14");
    lv_obj_set_style_text_color(ui_LabelHour3, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator9 = lv_label_create(ui_TimeContainer3);
    lv_obj_set_width(ui_LabelSeparator9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator9, -9);
    lv_obj_set_y(ui_LabelSeparator9, -5);
    lv_obj_set_align(ui_LabelSeparator9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator9, ":");
    lv_obj_set_style_text_color(ui_LabelSeparator9, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinute3 = lv_label_create(ui_TimeContainer3);
    lv_obj_set_width(ui_LabelMinute3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinute3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinute3, 15);
    lv_obj_set_y(ui_LabelMinute3, -3);
    lv_obj_set_align(ui_LabelMinute3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinute3, "30");
    lv_obj_set_style_text_color(ui_LabelMinute3, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinute3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinute3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer3 = lv_obj_create(ui_DirectionMaAxAndGy);
    lv_obj_remove_style_all(ui_DateContainer3);
    lv_obj_set_width(ui_DateContainer3, 115);
    lv_obj_set_height(ui_DateContainer3, 35);
    lv_obj_set_x(ui_DateContainer3, -123);
    lv_obj_set_y(ui_DateContainer3, -74);
    lv_obj_set_align(ui_DateContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDay3 = lv_label_create(ui_DateContainer3);
    lv_obj_set_width(ui_LabelDay3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay3, -7);
    lv_obj_set_y(ui_LabelDay3, 3);
    lv_obj_set_align(ui_LabelDay3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDay3, "24");
    lv_obj_set_style_text_color(ui_LabelDay3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator11 = lv_label_create(ui_DateContainer3);
    lv_obj_set_width(ui_LabelSeparator11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator11, 6);
    lv_obj_set_y(ui_LabelSeparator11, 3);
    lv_obj_set_align(ui_LabelSeparator11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator11, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMonth3 = lv_label_create(ui_DateContainer3);
    lv_obj_set_width(ui_LabelMonth3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMonth3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMonth3, 18);
    lv_obj_set_y(ui_LabelMonth3, 3);
    lv_obj_set_align(ui_LabelMonth3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMonth3, "03");
    lv_obj_set_style_text_color(ui_LabelMonth3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMonth3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMonth3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator7 = lv_label_create(ui_DateContainer3);
    lv_obj_set_width(ui_LabelSeparator7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator7, 31);
    lv_obj_set_y(ui_LabelSeparator7, 3);
    lv_obj_set_align(ui_LabelSeparator7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator7, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYear3 = lv_label_create(ui_DateContainer3);
    lv_obj_set_width(ui_LabelYear3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYear3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYear3, 43);
    lv_obj_set_y(ui_LabelYear3, 3);
    lv_obj_set_align(ui_LabelYear3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYear3, "26");
    lv_obj_set_style_text_color(ui_LabelYear3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYear3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYear3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DirectionContainer = lv_obj_create(ui_DirectionMaAxAndGy);
    lv_obj_remove_style_all(ui_DirectionContainer);
    lv_obj_set_width(ui_DirectionContainer, 161);
    lv_obj_set_height(ui_DirectionContainer, 169);
    lv_obj_set_x(ui_DirectionContainer, 6);
    lv_obj_set_y(ui_DirectionContainer, 30);
    lv_obj_set_align(ui_DirectionContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DirectionContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_degreDirection = lv_label_create(ui_DirectionContainer);
    lv_obj_set_width(ui_degreDirection, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_degreDirection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_degreDirection, 6);
    lv_obj_set_y(ui_degreDirection, -7);
    lv_obj_set_align(ui_degreDirection, LV_ALIGN_CENTER);
    lv_label_set_text(ui_degreDirection, "255 °");
    lv_obj_set_style_text_color(ui_degreDirection, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_degreDirection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_degreDirection, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_direction = lv_label_create(ui_DirectionContainer);
    lv_obj_set_width(ui_direction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_direction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_direction, -3);
    lv_obj_set_y(ui_direction, 34);
    lv_obj_set_align(ui_direction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_direction, "Ouest");
    lv_obj_set_style_text_color(ui_direction, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_direction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_direction, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge = lv_image_create(ui_DirectionContainer);
    lv_image_set_src(ui_gauge, &ui_img_logo_compass_28x28_v1_png);
    lv_obj_set_width(ui_gauge, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_gauge, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_gauge, -9);
    lv_obj_set_y(ui_gauge, 69);
    lv_obj_set_align(ui_gauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gauge, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_gauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_next3 = lv_image_create(ui_DirectionMaAxAndGy);
    lv_image_set_src(ui_next3, &ui_img_nav_button_right_circle_28x28_png);
    lv_obj_set_width(ui_next3, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_next3, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_next3, 126);
    lv_obj_set_y(ui_next3, 99);
    lv_obj_set_align(ui_next3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_previous3 = lv_image_create(ui_DirectionMaAxAndGy);
    lv_image_set_src(ui_previous3, &ui_img_nav_button_left_circle_28x28_png);
    lv_obj_set_width(ui_previous3, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_previous3, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_previous3, -133);
    lv_obj_set_y(ui_previous3, 100);
    lv_obj_set_align(ui_previous3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previous3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_previous3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CoordonnesAX = lv_obj_create(ui_DirectionMaAxAndGy);
    lv_obj_remove_style_all(ui_CoordonnesAX);
    lv_obj_set_width(ui_CoordonnesAX, 174);
    lv_obj_set_height(ui_CoordonnesAX, 103);
    lv_obj_set_x(ui_CoordonnesAX, 121);
    lv_obj_set_y(ui_CoordonnesAX, -88);
    lv_obj_set_align(ui_CoordonnesAX, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CoordonnesAX, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Axelorometer = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_Axelorometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Axelorometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Axelorometer, -66);
    lv_obj_set_y(ui_Axelorometer, -4);
    lv_obj_set_align(ui_Axelorometer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Axelorometer, "Acc");
    lv_obj_set_style_text_color(ui_Axelorometer, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Axelorometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordonnesAxlormeter = lv_obj_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_CoordonnesAxlormeter, 81);
    lv_obj_set_height(ui_CoordonnesAxlormeter, 48);
    lv_obj_set_x(ui_CoordonnesAxlormeter, -6);
    lv_obj_set_y(ui_CoordonnesAxlormeter, -2);
    lv_obj_set_align(ui_CoordonnesAxlormeter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CoordonnesAxlormeter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CoordonnesAxlormeter, lv_color_hex(0x096CF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoordonnesAxlormeter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CoordonnesAxlormeter, lv_color_hex(0x00AEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CoordonnesAxlormeter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CoordonnesAxlormeter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Xlabel = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_Xlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Xlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Xlabel, -31);
    lv_obj_set_y(ui_Xlabel, -18);
    lv_obj_set_align(ui_Xlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Xlabel, "X:");
    lv_obj_set_style_text_color(ui_Xlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Xlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Xlabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfX = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_valueOfX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfX, 7);
    lv_obj_set_y(ui_valueOfX, -17);
    lv_obj_set_align(ui_valueOfX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfX, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfX, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ylabel = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_Ylabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ylabel, -31);
    lv_obj_set_y(ui_Ylabel, -2);
    lv_obj_set_align(ui_Ylabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ylabel, "Y:");
    lv_obj_set_style_text_color(ui_Ylabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ylabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ylabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfY = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_valueOfY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfY, 7);
    lv_obj_set_y(ui_valueOfY, -2);
    lv_obj_set_align(ui_valueOfY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfY, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfY, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Zlabel = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_Zlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Zlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Zlabel, -30);
    lv_obj_set_y(ui_Zlabel, 13);
    lv_obj_set_align(ui_Zlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Zlabel, "Z:");
    lv_obj_set_style_text_color(ui_Zlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Zlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Zlabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfZ = lv_label_create(ui_CoordonnesAX);
    lv_obj_set_width(ui_valueOfZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfZ, 7);
    lv_obj_set_y(ui_valueOfZ, 13);
    lv_obj_set_align(ui_valueOfZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfZ, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfZ, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordonnesGY = lv_obj_create(ui_DirectionMaAxAndGy);
    lv_obj_remove_style_all(ui_CoordonnesGY);
    lv_obj_set_width(ui_CoordonnesGY, 174);
    lv_obj_set_height(ui_CoordonnesGY, 103);
    lv_obj_set_x(ui_CoordonnesGY, 121);
    lv_obj_set_y(ui_CoordonnesGY, -38);
    lv_obj_set_align(ui_CoordonnesGY, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CoordonnesGY, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GYRO = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_GYRO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GYRO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GYRO, -66);
    lv_obj_set_y(ui_GYRO, -3);
    lv_obj_set_align(ui_GYRO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GYRO, "Gyro");
    lv_obj_set_style_text_color(ui_GYRO, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GYRO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordonnesAxlormeter2 = lv_obj_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_CoordonnesAxlormeter2, 81);
    lv_obj_set_height(ui_CoordonnesAxlormeter2, 48);
    lv_obj_set_x(ui_CoordonnesAxlormeter2, -6);
    lv_obj_set_y(ui_CoordonnesAxlormeter2, -2);
    lv_obj_set_align(ui_CoordonnesAxlormeter2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CoordonnesAxlormeter2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CoordonnesAxlormeter2, lv_color_hex(0x096CF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoordonnesAxlormeter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CoordonnesAxlormeter2, lv_color_hex(0x00AEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CoordonnesAxlormeter2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CoordonnesAxlormeter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Xlabel2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_Xlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Xlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Xlabel2, -29);
    lv_obj_set_y(ui_Xlabel2, -17);
    lv_obj_set_align(ui_Xlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Xlabel2, "X:");
    lv_obj_set_style_text_color(ui_Xlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Xlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Xlabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfX2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_valueOfX2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfX2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfX2, 7);
    lv_obj_set_y(ui_valueOfX2, -16);
    lv_obj_set_align(ui_valueOfX2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfX2, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfX2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfX2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfX2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ylabel2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_Ylabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ylabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ylabel2, -29);
    lv_obj_set_y(ui_Ylabel2, -2);
    lv_obj_set_align(ui_Ylabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ylabel2, "Y:");
    lv_obj_set_style_text_color(ui_Ylabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ylabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ylabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfY2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_valueOfY2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfY2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfY2, 7);
    lv_obj_set_y(ui_valueOfY2, -2);
    lv_obj_set_align(ui_valueOfY2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfY2, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfY2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfY2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfY2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Zlabel2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_Zlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Zlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Zlabel2, -29);
    lv_obj_set_y(ui_Zlabel2, 13);
    lv_obj_set_align(ui_Zlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Zlabel2, "Z:");
    lv_obj_set_style_text_color(ui_Zlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Zlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Zlabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valueOfZ2 = lv_label_create(ui_CoordonnesGY);
    lv_obj_set_width(ui_valueOfZ2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueOfZ2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueOfZ2, 7);
    lv_obj_set_y(ui_valueOfZ2, 13);
    lv_obj_set_align(ui_valueOfZ2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueOfZ2, "+9.6");
    lv_obj_set_style_text_color(ui_valueOfZ2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueOfZ2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueOfZ2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Coordonnes2 = lv_image_create(ui_CoordonnesGY);
    lv_image_set_src(ui_Coordonnes2, &ui_img_xyz_30x30_exact_png);
    lv_obj_set_width(ui_Coordonnes2, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Coordonnes2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Coordonnes2, -66);
    lv_obj_set_y(ui_Coordonnes2, -27);
    lv_obj_set_align(ui_Coordonnes2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Coordonnes2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Coordonnes2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_DirectionMaAxAndGy_screen_destroy(void)
{
    if(ui_DirectionMaAxAndGy) lv_obj_del(ui_DirectionMaAxAndGy);

    // NULL screen variables
    ui_DirectionMaAxAndGy = NULL;
    ui_Bakground1 = NULL;
    ui_TimeContainer3 = NULL;
    ui_LabelHour3 = NULL;
    ui_LabelSeparator9 = NULL;
    ui_LabelMinute3 = NULL;
    ui_DateContainer3 = NULL;
    ui_LabelDay3 = NULL;
    ui_LabelSeparator11 = NULL;
    ui_LabelMonth3 = NULL;
    ui_LabelSeparator7 = NULL;
    ui_LabelYear3 = NULL;
    ui_DirectionContainer = NULL;
    ui_degreDirection = NULL;
    ui_direction = NULL;
    ui_gauge = NULL;
    ui_next3 = NULL;
    ui_previous3 = NULL;
    ui_CoordonnesAX = NULL;
    ui_Axelorometer = NULL;
    ui_CoordonnesAxlormeter = NULL;
    ui_Xlabel = NULL;
    ui_valueOfX = NULL;
    ui_Ylabel = NULL;
    ui_valueOfY = NULL;
    ui_Zlabel = NULL;
    ui_valueOfZ = NULL;
    ui_CoordonnesGY = NULL;
    ui_GYRO = NULL;
    ui_CoordonnesAxlormeter2 = NULL;
    ui_Xlabel2 = NULL;
    ui_valueOfX2 = NULL;
    ui_Ylabel2 = NULL;
    ui_valueOfY2 = NULL;
    ui_Zlabel2 = NULL;
    ui_valueOfZ2 = NULL;
    ui_Coordonnes2 = NULL;

}
