// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_DIRECTIONMAAXANDGY_H
#define UI_DIRECTIONMAAXANDGY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DirectionMaAxAndGy
extern void ui_DirectionMaAxAndGy_screen_init(void);
extern void ui_DirectionMaAxAndGy_screen_destroy(void);
extern lv_obj_t * ui_DirectionMaAxAndGy;
extern lv_obj_t * ui_Bakground1;
extern lv_obj_t * ui_TimeContainer3;
extern lv_obj_t * ui_LabelHour3;
extern lv_obj_t * ui_LabelSeparator9;
extern lv_obj_t * ui_LabelMinute3;
extern lv_obj_t * ui_DateContainer3;
extern lv_obj_t * ui_LabelDay3;
extern lv_obj_t * ui_LabelSeparator11;
extern lv_obj_t * ui_LabelMonth3;
extern lv_obj_t * ui_LabelSeparator7;
extern lv_obj_t * ui_LabelYear3;
extern lv_obj_t * ui_DirectionContainer;
extern lv_obj_t * ui_degreDirection;
extern lv_obj_t * ui_direction;
extern lv_obj_t * ui_gauge;
extern lv_obj_t * ui_next3;
extern lv_obj_t * ui_previous3;
extern lv_obj_t * ui_CoordonnesAX;
extern lv_obj_t * ui_Axelorometer;
extern lv_obj_t * ui_CoordonnesAxlormeter;
extern lv_obj_t * ui_Xlabel;
extern lv_obj_t * ui_valueOfX;
extern lv_obj_t * ui_Ylabel;
extern lv_obj_t * ui_valueOfY;
extern lv_obj_t * ui_Zlabel;
extern lv_obj_t * ui_valueOfZ;
extern lv_obj_t * ui_CoordonnesGY;
extern lv_obj_t * ui_GYRO;
extern lv_obj_t * ui_CoordonnesAxlormeter2;
extern lv_obj_t * ui_Xlabel2;
extern lv_obj_t * ui_valueOfX2;
extern lv_obj_t * ui_Ylabel2;
extern lv_obj_t * ui_valueOfY2;
extern lv_obj_t * ui_Zlabel2;
extern lv_obj_t * ui_valueOfZ2;
extern lv_obj_t * ui_Coordonnes2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

