// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomePage
extern void ui_HomePage_screen_init(void);
extern void ui_HomePage_screen_destroy(void);
extern lv_obj_t * ui_HomePage;
extern lv_obj_t * ui_HomePag;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelSeparator;
extern lv_obj_t * ui_LabelMinute;
extern lv_obj_t * ui_DateContainer;
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_LabelSeparator2;
extern lv_obj_t * ui_LabelMonth;
extern lv_obj_t * ui_LabelSeparator3;
extern lv_obj_t * ui_LabelYear;
extern lv_obj_t * ui_ContainerWeather;
extern lv_obj_t * ui_DegreCeluis;
extern lv_obj_t * ui_next;
extern lv_obj_t * ui_previous;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

