// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_HomePage = NULL;
lv_obj_t * ui_HomePag = NULL;
lv_obj_t * ui_TimeContainer = NULL;
lv_obj_t * ui_LabelHour = NULL;
lv_obj_t * ui_LabelSeparator = NULL;
lv_obj_t * ui_LabelMinute = NULL;
lv_obj_t * ui_DateContainer = NULL;
lv_obj_t * ui_LabelDay = NULL;
lv_obj_t * ui_LabelSeparator2 = NULL;
lv_obj_t * ui_LabelMonth = NULL;
lv_obj_t * ui_LabelSeparator3 = NULL;
lv_obj_t * ui_LabelYear = NULL;
lv_obj_t * ui_ContainerWeather = NULL;
lv_obj_t * ui_DegreCeluis = NULL;
lv_obj_t * ui_next = NULL;
lv_obj_t * ui_previous = NULL;
// event funtions

// build funtions

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomePag = lv_image_create(ui_HomePage);
    lv_image_set_src(ui_HomePag, &ui_img_home_page_png);
    lv_obj_set_width(ui_HomePag, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_HomePag, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_HomePag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomePag, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_HomePag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeContainer = lv_obj_create(ui_HomePage);
    lv_obj_remove_style_all(ui_TimeContainer);
    lv_obj_set_width(ui_TimeContainer, 140);
    lv_obj_set_height(ui_TimeContainer, 60);
    lv_obj_set_x(ui_TimeContainer, 6);
    lv_obj_set_y(ui_TimeContainer, -9);
    lv_obj_set_align(ui_TimeContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHour = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_LabelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour, -44);
    lv_obj_set_y(ui_LabelHour, -1);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour, "14");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_LabelSeparator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator, -9);
    lv_obj_set_y(ui_LabelSeparator, -5);
    lv_obj_set_align(ui_LabelSeparator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator, ":");
    lv_obj_set_style_text_color(ui_LabelSeparator, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinute = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_LabelMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinute, 31);
    lv_obj_set_y(ui_LabelMinute, -1);
    lv_obj_set_align(ui_LabelMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinute, "30");
    lv_obj_set_style_text_color(ui_LabelMinute, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinute, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer = lv_obj_create(ui_HomePage);
    lv_obj_remove_style_all(ui_DateContainer);
    lv_obj_set_width(ui_DateContainer, 115);
    lv_obj_set_height(ui_DateContainer, 35);
    lv_obj_set_x(ui_DateContainer, -12);
    lv_obj_set_y(ui_DateContainer, 26);
    lv_obj_set_align(ui_DateContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDay = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_LabelDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay, -22);
    lv_obj_set_y(ui_LabelDay, 4);
    lv_obj_set_align(ui_LabelDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDay, "24");
    lv_obj_set_style_text_color(ui_LabelDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator2 = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_LabelSeparator2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator2, -4);
    lv_obj_set_y(ui_LabelSeparator2, 3);
    lv_obj_set_align(ui_LabelSeparator2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator2, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMonth = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_LabelMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMonth, 12);
    lv_obj_set_y(ui_LabelMonth, 4);
    lv_obj_set_align(ui_LabelMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMonth, "03");
    lv_obj_set_style_text_color(ui_LabelMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMonth, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator3 = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_LabelSeparator3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator3, 31);
    lv_obj_set_y(ui_LabelSeparator3, 3);
    lv_obj_set_align(ui_LabelSeparator3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator3, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYear = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_LabelYear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYear, 48);
    lv_obj_set_y(ui_LabelYear, 3);
    lv_obj_set_align(ui_LabelYear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYear, "26");
    lv_obj_set_style_text_color(ui_LabelYear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYear, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWeather = lv_obj_create(ui_HomePage);
    lv_obj_remove_style_all(ui_ContainerWeather);
    lv_obj_set_width(ui_ContainerWeather, 91);
    lv_obj_set_height(ui_ContainerWeather, 40);
    lv_obj_set_x(ui_ContainerWeather, 2);
    lv_obj_set_y(ui_ContainerWeather, -85);
    lv_obj_set_align(ui_ContainerWeather, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DegreCeluis = lv_label_create(ui_ContainerWeather);
    lv_obj_set_width(ui_DegreCeluis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DegreCeluis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DegreCeluis, -6);
    lv_obj_set_y(ui_DegreCeluis, -1);
    lv_obj_set_align(ui_DegreCeluis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DegreCeluis, "25 °C");
    lv_obj_set_style_text_color(ui_DegreCeluis, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DegreCeluis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DegreCeluis, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next = lv_image_create(ui_HomePage);
    lv_image_set_src(ui_next, &ui_img_nav_button_right_circle_28x28_png);
    lv_obj_set_width(ui_next, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_next, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_next, 126);
    lv_obj_set_y(ui_next, 99);
    lv_obj_set_align(ui_next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_previous = lv_image_create(ui_HomePage);
    lv_image_set_src(ui_previous, &ui_img_nav_button_left_circle_28x28_png);
    lv_obj_set_width(ui_previous, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_previous, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_previous, -133);
    lv_obj_set_y(ui_previous, 100);
    lv_obj_set_align(ui_previous, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previous, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_previous, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_HomePage_screen_destroy(void)
{
    if(ui_HomePage) lv_obj_del(ui_HomePage);

    // NULL screen variables
    ui_HomePage = NULL;
    ui_HomePag = NULL;
    ui_TimeContainer = NULL;
    ui_LabelHour = NULL;
    ui_LabelSeparator = NULL;
    ui_LabelMinute = NULL;
    ui_DateContainer = NULL;
    ui_LabelDay = NULL;
    ui_LabelSeparator2 = NULL;
    ui_LabelMonth = NULL;
    ui_LabelSeparator3 = NULL;
    ui_LabelYear = NULL;
    ui_ContainerWeather = NULL;
    ui_DegreCeluis = NULL;
    ui_next = NULL;
    ui_previous = NULL;

}
