// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_Image47 = NULL;
lv_obj_t * ui_TimeContainer2 = NULL;
lv_obj_t * ui_LabelHour2 = NULL;
lv_obj_t * ui_LabelSeparator4 = NULL;
lv_obj_t * ui_LabelMinute2 = NULL;
lv_obj_t * ui_DateContainer2 = NULL;
lv_obj_t * ui_LabelDay2 = NULL;
lv_obj_t * ui_LabelSeparator6 = NULL;
lv_obj_t * ui_LabelMonth2 = NULL;
lv_obj_t * ui_LabelSeparator1 = NULL;
lv_obj_t * ui_LabelYear2 = NULL;
lv_obj_t * ui_ContainerHumidite = NULL;
lv_obj_t * ui_humidite = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_ContainerWeather2 = NULL;
lv_obj_t * ui_cloud2 = NULL;
lv_obj_t * ui_DegreCeluis2 = NULL;
lv_obj_t * ui_ContainerPressure = NULL;
lv_obj_t * ui_PressureGauge = NULL;
lv_obj_t * ui_Pressure = NULL;
lv_obj_t * ui_next2 = NULL;
lv_obj_t * ui_previous2 = NULL;
// event funtions

// build funtions

void ui_Weather_screen_init(void)
{
    ui_Weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image47 = lv_image_create(ui_Weather);
    lv_image_set_src(ui_Image47, &ui_img_home_page_png);
    lv_obj_set_width(ui_Image47, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image47, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeContainer2 = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_TimeContainer2);
    lv_obj_set_width(ui_TimeContainer2, 140);
    lv_obj_set_height(ui_TimeContainer2, 39);
    lv_obj_set_x(ui_TimeContainer2, -61);
    lv_obj_set_y(ui_TimeContainer2, -90);
    lv_obj_set_align(ui_TimeContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHour2 = lv_label_create(ui_TimeContainer2);
    lv_obj_set_width(ui_LabelHour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour2, -44);
    lv_obj_set_y(ui_LabelHour2, -1);
    lv_obj_set_align(ui_LabelHour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour2, "14");
    lv_obj_set_style_text_color(ui_LabelHour2, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator4 = lv_label_create(ui_TimeContainer2);
    lv_obj_set_width(ui_LabelSeparator4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator4, -9);
    lv_obj_set_y(ui_LabelSeparator4, -5);
    lv_obj_set_align(ui_LabelSeparator4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator4, ":");
    lv_obj_set_style_text_color(ui_LabelSeparator4, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinute2 = lv_label_create(ui_TimeContainer2);
    lv_obj_set_width(ui_LabelMinute2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinute2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinute2, 31);
    lv_obj_set_y(ui_LabelMinute2, -1);
    lv_obj_set_align(ui_LabelMinute2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinute2, "30");
    lv_obj_set_style_text_color(ui_LabelMinute2, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinute2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinute2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer2 = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_DateContainer2);
    lv_obj_set_width(ui_DateContainer2, 115);
    lv_obj_set_height(ui_DateContainer2, 35);
    lv_obj_set_x(ui_DateContainer2, 35);
    lv_obj_set_y(ui_DateContainer2, -80);
    lv_obj_set_align(ui_DateContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDay2 = lv_label_create(ui_DateContainer2);
    lv_obj_set_width(ui_LabelDay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay2, -22);
    lv_obj_set_y(ui_LabelDay2, 4);
    lv_obj_set_align(ui_LabelDay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDay2, "24");
    lv_obj_set_style_text_color(ui_LabelDay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator6 = lv_label_create(ui_DateContainer2);
    lv_obj_set_width(ui_LabelSeparator6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator6, -4);
    lv_obj_set_y(ui_LabelSeparator6, 3);
    lv_obj_set_align(ui_LabelSeparator6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator6, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMonth2 = lv_label_create(ui_DateContainer2);
    lv_obj_set_width(ui_LabelMonth2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMonth2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMonth2, 12);
    lv_obj_set_y(ui_LabelMonth2, 4);
    lv_obj_set_align(ui_LabelMonth2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMonth2, "03");
    lv_obj_set_style_text_color(ui_LabelMonth2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMonth2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMonth2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeparator1 = lv_label_create(ui_DateContainer2);
    lv_obj_set_width(ui_LabelSeparator1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSeparator1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSeparator1, 31);
    lv_obj_set_y(ui_LabelSeparator1, 3);
    lv_obj_set_align(ui_LabelSeparator1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeparator1, "/");
    lv_obj_set_style_text_color(ui_LabelSeparator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeparator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeparator1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYear2 = lv_label_create(ui_DateContainer2);
    lv_obj_set_width(ui_LabelYear2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYear2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYear2, 48);
    lv_obj_set_y(ui_LabelYear2, 3);
    lv_obj_set_align(ui_LabelYear2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYear2, "26");
    lv_obj_set_style_text_color(ui_LabelYear2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYear2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYear2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerHumidite = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_ContainerHumidite);
    lv_obj_set_width(ui_ContainerHumidite, 107);
    lv_obj_set_height(ui_ContainerHumidite, 37);
    lv_obj_set_x(ui_ContainerHumidite, -46);
    lv_obj_set_y(ui_ContainerHumidite, 69);
    lv_obj_set_align(ui_ContainerHumidite, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerHumidite, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidite = lv_image_create(ui_ContainerHumidite);
    lv_image_set_src(ui_humidite, &ui_img_rain_png);
    lv_obj_set_width(ui_humidite, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_humidite, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_humidite, -29);
    lv_obj_set_y(ui_humidite, -1);
    lv_obj_set_align(ui_humidite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidite, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_humidite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_ContainerHumidite);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 14);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "17%");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWeather2 = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_ContainerWeather2);
    lv_obj_set_width(ui_ContainerWeather2, 122);
    lv_obj_set_height(ui_ContainerWeather2, 40);
    lv_obj_set_x(ui_ContainerWeather2, 69);
    lv_obj_set_y(ui_ContainerWeather2, -30);
    lv_obj_set_align(ui_ContainerWeather2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerWeather2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloud2 = lv_image_create(ui_ContainerWeather2);
    lv_image_set_src(ui_cloud2, &ui_img_weather_png);
    lv_obj_set_width(ui_cloud2, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_cloud2, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_cloud2, 34);
    lv_obj_set_y(ui_cloud2, -2);
    lv_obj_set_align(ui_cloud2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cloud2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_cloud2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DegreCeluis2 = lv_label_create(ui_ContainerWeather2);
    lv_obj_set_width(ui_DegreCeluis2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DegreCeluis2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DegreCeluis2, -17);
    lv_obj_set_y(ui_DegreCeluis2, -1);
    lv_obj_set_align(ui_DegreCeluis2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DegreCeluis2, "25 °C");
    lv_obj_set_style_text_color(ui_DegreCeluis2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DegreCeluis2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DegreCeluis2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPressure = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_ContainerPressure);
    lv_obj_set_width(ui_ContainerPressure, 156);
    lv_obj_set_height(ui_ContainerPressure, 26);
    lv_obj_set_x(ui_ContainerPressure, 16);
    lv_obj_set_y(ui_ContainerPressure, 17);
    lv_obj_set_align(ui_ContainerPressure, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerPressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PressureGauge = lv_image_create(ui_ContainerPressure);
    lv_image_set_src(ui_PressureGauge, &ui_img_logo_pressure_gauge_28x28_png);
    lv_obj_set_width(ui_PressureGauge, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_PressureGauge, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_PressureGauge, -61);
    lv_obj_set_y(ui_PressureGauge, -2);
    lv_obj_set_align(ui_PressureGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PressureGauge, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PressureGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pressure = lv_label_create(ui_ContainerPressure);
    lv_obj_set_width(ui_Pressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pressure, 11);
    lv_obj_set_y(ui_Pressure, -2);
    lv_obj_set_align(ui_Pressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pressure, "1000mPa");
    lv_obj_set_style_text_color(ui_Pressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next2 = lv_image_create(ui_Weather);
    lv_image_set_src(ui_next2, &ui_img_nav_button_right_circle_28x28_png);
    lv_obj_set_width(ui_next2, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_next2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_next2, 126);
    lv_obj_set_y(ui_next2, 99);
    lv_obj_set_align(ui_next2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_next2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_previous2 = lv_image_create(ui_Weather);
    lv_image_set_src(ui_previous2, &ui_img_nav_button_left_circle_28x28_png);
    lv_obj_set_width(ui_previous2, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_previous2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_previous2, -133);
    lv_obj_set_y(ui_previous2, 100);
    lv_obj_set_align(ui_previous2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previous2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_previous2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Weather_screen_destroy(void)
{
    if(ui_Weather) lv_obj_del(ui_Weather);

    // NULL screen variables
    ui_Weather = NULL;
    ui_Image47 = NULL;
    ui_TimeContainer2 = NULL;
    ui_LabelHour2 = NULL;
    ui_LabelSeparator4 = NULL;
    ui_LabelMinute2 = NULL;
    ui_DateContainer2 = NULL;
    ui_LabelDay2 = NULL;
    ui_LabelSeparator6 = NULL;
    ui_LabelMonth2 = NULL;
    ui_LabelSeparator1 = NULL;
    ui_LabelYear2 = NULL;
    ui_ContainerHumidite = NULL;
    ui_humidite = NULL;
    ui_Label9 = NULL;
    ui_ContainerWeather2 = NULL;
    ui_cloud2 = NULL;
    ui_DegreCeluis2 = NULL;
    ui_ContainerPressure = NULL;
    ui_PressureGauge = NULL;
    ui_Pressure = NULL;
    ui_next2 = NULL;
    ui_previous2 = NULL;

}
