// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Weather
extern void ui_Weather_screen_init(void);
extern void ui_Weather_screen_destroy(void);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Image47;
extern lv_obj_t * ui_TimeContainer2;
extern lv_obj_t * ui_LabelHour2;
extern lv_obj_t * ui_LabelSeparator4;
extern lv_obj_t * ui_LabelMinute2;
extern lv_obj_t * ui_DateContainer2;
extern lv_obj_t * ui_LabelDay2;
extern lv_obj_t * ui_LabelSeparator6;
extern lv_obj_t * ui_LabelMonth2;
extern lv_obj_t * ui_LabelSeparator1;
extern lv_obj_t * ui_LabelYear2;
extern lv_obj_t * ui_ContainerHumidite;
extern lv_obj_t * ui_humidite;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_ContainerWeather2;
extern lv_obj_t * ui_cloud2;
extern lv_obj_t * ui_DegreCeluis2;
extern lv_obj_t * ui_ContainerPressure;
extern lv_obj_t * ui_PressureGauge;
extern lv_obj_t * ui_Pressure;
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_previous2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

